import webpush from "web-push";
import { createAdminClient } from "@/lib/supabase/admin";

type Payload={title:string;body:string;url?:string;tag?:string;ticketNumber?:number};
type PushError=Error&{statusCode?:number;body?:string};
function configure(){const pub=process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY;const priv=process.env.VAPID_PRIVATE_KEY;const subject=process.env.VAPID_SUBJECT;if(!pub||!priv||!subject)throw new Error("VAPID_CONFIG_MISSING");webpush.setVapidDetails(subject,pub,priv)}
async function sendRows(rows:any[],payload:Payload){configure();const admin=createAdminClient();let success=0,failed=0;console.log(`[KLIKAO PUSH START] subscriptions=${rows.length}`);for(const row of rows){try{const response=await webpush.sendNotification({endpoint:row.endpoint,keys:{p256dh:row.p256dh,auth:row.auth}},JSON.stringify(payload),{TTL:60});success++;console.log(`[KLIKAO PUSH SUCCESS] id=${row.id} status=${response.statusCode}`)}catch(raw){failed++;const error=raw as PushError;console.error(`[KLIKAO PUSH FAILED] id=${row.id} status=${error.statusCode??"unknown"}`,error.body??error.message);if(error.statusCode===404||error.statusCode===410){await admin.from("admin_push_subscriptions").delete().eq("id",row.id);console.log(`[KLIKAO PUSH CLEANUP] removed=${row.id}`)}}}return{success,failed,total:rows.length}}
export async function sendPushToAdmins(payload:Payload){const admin=createAdminClient();const{data,error}=await admin.from("admin_push_subscriptions").select("id,user_id,endpoint,p256dh,auth");if(error)throw error;return sendRows(data??[],payload)}
export async function sendPushToAdminUser(userId:string,payload:Payload){const admin=createAdminClient();const{data,error}=await admin.from("admin_push_subscriptions").select("id,user_id,endpoint,p256dh,auth").eq("user_id",userId);if(error)throw error;return sendRows(data??[],payload)}
